version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: study_spots_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: study_spots_db
    volumes:
      - mongo_data:/data/db

  web:
    build: .
    container_name: study_spots_app
    ports:
      - "5000:5000"
    environment:
      MONGO_USER: admin
      MONGO_PASSWORD: secret
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DBNAME: study_spots_db
    depends_on:
      - mongo

volumes:
  mongo_data: